#If for some reason you want to disable this plugin, just set this to 'false'. Default: true.
enable-plugin: true

#Should administrators be warned about new updates? Default: true.
#If 'true', this will not bother you while you are playing. I promisse!
update:
    check: true
    #download: true # Work in progress feature!

#List here worlds where LT Sleep N Storm must work (nether and the_end are disabled by default).
worlds:
    - world
#Do not change this under any circumstances!
config-version: 1