#
# Copyright (C) 2019 Murilo Amaral Nappi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

#If for some reason you want to disable this plugin, just set this to 'false'. Default: true.
enable-plugin: true

#INTERNAL languages available: portuguese, english. Default: english
language: english

#Should administrators be warned about new updates? Default: true.
#If 'true', this will not bother you while you are playing. I promisse!
update:
    check: true
    #download: true # Work in progress feature!

#List here worlds where LT Sleep N Storm must work (NETHER and THE_END environments are disabled by default).
worlds:
    - world

#Do not change this under any circumstances!
config-version: 1