#If for some reason you want to disable this plugin, just set this to 'false'. Default: true.
enable-plugin: true

#INTERNAL languages available: portuguese, english. Default: english
language: english

#Should administrators be warned about new updates? Default: true.
#If 'true', this will not bother you while you are playing. I promisse!
update:
    check: true

#List here worlds where LT Sleep N Storm must work (NETHER and THE_END environments are disabled by default).
worlds:
    - world

#After this timeout in seconds, the player will be set as "in Rest Mode".
#The Rest Mode will prevent players from getting tired while AFK.
auto-restmode: 300

#Do not change this under any circumstances!
config-version: 2