name: LTSleepNStorm
description: A new sleeping system in Minecraft 1.13.x.
version: 0.2.0
api-version: 1.13
load: STARTUP
author: [leothawne]
website: https://leothawne.github.io/LTSleepNStorm/
url: https://leothawne.github.io/LTSleepNStorm/
main: io.github.leothawne.LTSleepNStorm.LTSleepNStorm
database: false
commands:
    sleepnstorm:
        description: A LT Sleep N Storm command.
        aliases: [sns]
        usage: /<command>
    sleepnstormadmin:
        description: A LT Sleep N Storm command.
        aliases: [snsa]
        usage: /<command>
    sleep:
        description: A LT Sleep N Storm command.
        usage: /<command>
permissions:
    LTSleepNStorm.use:
        description: A LT Sleep N Storm permission node.
        default: true
    LTSleepNStorm.sleep:
        description: A LT Sleep N Storm permission node.
        default: true
    LTSleepNStorm.sleep.bypass:
        description: A LT Sleep N Storm permission node.
        default: op
    LTSleepNStorm.sleep.command:
        description: A LT Sleep N Storm permission node.
        default: op
    LTSleepNStorm.admin:
        description: A LT Sleep N Storm permission node.
        default: op