name: LTSleepNStorm
description: A new way of sleeping in 1.13.
version: 0.1.0
api-version: 1.13
load: STARTUP
author: [leothawne]
website: https://leothawne.github.io/LTSleepNStorm/
url: https://leothawne.github.io/LTSleepNStorm/
main: io.github.leothawne.LTSleepNStorm.LTSleepNStormLoader
database: false
commands:
    sleepnstorm:
        description: All available commands for LT Sleep N Storm.
        aliases: [sns]
        usage: /<command>
    sleepnstormadmin:
        description: All admin commands for LT Sleep N Storm.
        aliases: [snsa]
        usage: /<command>
permissions:
    LTSleepNStorm.use:
        description: Allow players to use LTSNS commands.
        default: true
    LTSleepNStorm.sleep:
        description: Allow players to use the new sleeping mechanic.
        default: true
    LTSleepNStorm.admin:
        description: Allow admins to use LTSNS admin commands.
        default: op